source ./unans_env/bin/activate
export PYTHONPATH=.; export TOKENIZERS_PARALLELISM=true

python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=300  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 300
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=303  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 303
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=308  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 308
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=309  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 309
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=310  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 310
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=334  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 334
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=335  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 335
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=343  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 343
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=351  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 351
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=352  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 352
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=365  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 365
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=367  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 367
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=372  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 372
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=373  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 373
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=377  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 377
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=380  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 380
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=382  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 382
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=383  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 383
python ./src/crumqs_generation/run.py  --database_dir=./_database/neuclir_test  --report_requests_path=./_database/test_requests_neuclir.jsonl  --num_articles_to_crawl=25  --num_topics=25  --dataset_test_size=100  --exp_name=388  --save_dir=./generated_data/mh_neuclir  --max_q_prompts_per_request=100  --max_unanswerable_qs_per_request=100  --max_node_dicts=100  --max_per_split=25  --ids_to_run 388 